### ISSUE TITLE
Should Filter specs implement Specification interface?

### ISSUE THREAD

**Issue by Strontium-90** [Happyr/Doctrine-Specification#116]
Its imposible now
```php
$repository->match(Spec::eq('name', 'foo'))
```
but this works
```php
$repository->match(Spec::orX(
    Spec::eq('name', 'foo'),
    Spec::eq('name', 'bar')   
))
```

Should Comparisons implements Specification interface? Or repository method `match` should be like:
```php
public function match($specification
      //....
        if ($specification instanceof QueryModifier) {
            $specification->modify($queryBuilder, $this->getAlias());
        }
        if ($specification instanceof Filter) {
            $queryBuilder->where($specification->getFilter($queryBuilder, $this->getAlias()));
        }
```

**Comment by Nyholm** [comment]
You are right. Thank you for this. I don't know when we made this mistake. 

We should remove the type annotation on the functions in the `EntitySpecificationRepositoryTrait` and make the extra checks as you suggests. I believe that we aslo should throw an exception if you don't use a `Filter` or a ´QueryModifier`. 

Would you mind sending a PR?

**Comment by Strontium-90** [comment]
>Would you mind sending a PR?

@Nyholm, PR is here #118.

**Comment by Nyholm** [comment]
Looking at it now
