### ISSUE TITLE
CountOf or having usage?

### ISSUE THREAD

**Issue by PavelJurasek** [Happyr/Doctrine-Specification#126]
Hi, 

I'm wondering if it is possible to use these functions to filter out entities that do not have any related records, e.g.: Select all galleries that have at least 1 photo added to it.

I expected something like `Spec::gt(Spec::countOf('photos'), 0)` would work but it doesn't. I also unsuccessfully tried `Spec::gt('COUNT(photos)', 0)`.

Thanks!

**Comment by Nyholm** [comment]
Interesting use case. As you discovered, that is not supported atm. But I believe that feature should be on the wish list.

**Comment by peter-gribanov** [comment]
Now you can using functions in specification:
```php
$spec = Spec::gt(Spec::COUNT('photos'), 0);
```
