### ISSUE TITLE
Add Doctrine like addGroupBy methods

### ISSUE THREAD

**Issue by webdevilopers** [Happyr/Doctrine-Specification#130]
I'm not sure if it is a common approach to use Specs for adding GROUP BY only.

Before I had a single repository method:

``` php
    public function getTotalParttypes(
        array $criteria = null,
        $groupByIntegratorNumber = false,
        $groupByShippingNumber = false,
        $groupByDate = false,
        $groupByLocation = false
    ) {}
```

There are about several use cases - use all the grouping or at least one or two at the same time.

I added a spec for each grouping case:

``` php
        $spec = Spec::andX(
            new DoctrineGroupFooSpecification(),
            new DoctrineGroupBarSpecification()
        );
```

Unfortunately - though I am using `andX` every next groupBy overrides the previous:

``` php
class DoctrineGroupBarSpecification
    extends BaseSpecification
{
    public function getSpec()
    {
        return Spec::groupBy('bar');
    }
```

Currently I use this spec for all grouping using the query builder `addGroupBy` method:

``` php
    public function modify(QueryBuilder $qb, $dqlAlias)
    {
        $qb
            ->addGroupBy($dqlAlias . '.date')
            ->addGroupBy($dqlAlias . '.shippingnumber')
            ->addGroupBy('p.integratorNumber')
            ->addGroupBy($dqlAlias . '.location');
    }
```

Using the `modify` method I could add each grouping via `addGroupBy` on the query builder.

I just expected the `andX` spec to us the `addGroupBy` method and not override existing grouping.

Should this behaviour be improved?

**Comment by peter-gribanov** [comment]
> Unfortunately - though I am using andX every next groupBy overrides the previous

This should not be. The specification [uses](https://github.com/Happyr/Doctrine-Specification/blob/9ac91cd0f84ed68d40279b22827ef7fba847204a/src/Query/GroupBy.php#L38) the `addGroupBy()` method.

**Comment by webdevilopers** [comment]
Unfortunately I no longer work on that project. Closing therefore.
