### ISSUE TITLE
Problems of code style

### ISSUE THREAD

**Issue by peter-gribanov** [Happyr/Doctrine-Specification#138]
You have many problems of code style.
See the [report](https://styleci.io/analyses/zeLBl9).

I add StyleCI [config](https://github.com/peter-gribanov/Doctrine-Specification/blob/styleci/.styleci.yml) for use [Symfony](https://styleci.readme.io/docs/presets#section-symfony) code style presets.

I can make PR for fix it.
You need it?

**Comment by peter-gribanov** [comment]
You can use a fixer [ordered_class_elements](https://styleci.readme.io/docs/fixers#section-ordered_class_elements) to comply with the [contributing rule](https://github.com/Happyr/Doctrine-Specification/blob/master/CONTRIBUTING.md#projects-standards):

> Keep the order of class elements: static properties, instance properties, constructor, destructor, static methods, instance methods, magic static methods, magic instance methods.

**Comment by Nyholm** [comment]
Sure. Im happy to!

**Comment by Nyholm** [comment]
I've enabled Style CI for this repo now
