### ISSUE TITLE
Single Scalar Result

### ISSUE THREAD

**Issue by peter-gribanov** [Happyr/Doctrine-Specification#142]
What about `matchSingleScalarResult()` ?

`CountOf` specification return single scalar result, but there is no normal way to get it.

```php
$result = $rep->matchSingleResult(Spec::countOf(new MySpec()));
return (int)current($result);
```

or

```php
return (int)$rep->getQuery(Spec::countOf(new MySpec()))->getSingleScalarResult();
```

It might be better to add a method `matchSingleScalarResult()` to the repository?

```php
return (int)$rep->matchSingleScalarResult(Spec::countOf(new MySpec()));
```

**Comment by peter-gribanov** [comment]
Sorry
I did not notice [AsSingleScalar](https://github.com/Happyr/Doctrine-Specification/blob/master/src/Result/AsSingleScalar.php).

Then need to use like this:

```php
return (int)$rep->match(Spec::countOf(new MySpec()), new AsSingleScalar());
```

**Comment by Nyholm** [comment]
>I did not notice AsSingleScalar.

Yes. exactly =)

**Comment by peter-gribanov** [comment]
> I did not notice [AsSingleScalar](https://github.com/Happyr/Doctrine-Specification/blob/master/src/Result/AsSingleScalar.php).

Although, i still think that one method is more convenient
