### ISSUE TITLE
Spec comparison methods do not support specifying custom parameter type

### ISSUE THREAD

**Issue by ste93cry** [Happyr/Doctrine-Specification#161]
The comparison methods of the `Spec` class (e.g. `isNull`, `eq`, etc) do not support specifying a custom [Doctrine parameter type](https://github.com/doctrine/doctrine2/blob/bbc1ed93b14e079cd403cb5b2b1134da35af431e/lib/Doctrine/ORM/QueryBuilder.php#L529). when setting the parameters of a query. This is a problem for example when going to compare dates, as the [Doctrine ParameterTypeInferer](https://github.com/doctrine/doctrine2/blob/bbc1ed93b14e079cd403cb5b2b1134da35af431e/lib/Doctrine/ORM/Query/ParameterTypeInferer.php#L40) will always convert any class implementing the `\DateTimeInterface` to the format returned by `Doctrine\DBAL\Platforms\Platform::getDateTimeFormatString()` even if the column type is `date` because it uses `datetime` as parameter type. The only way to skip this behaviour is to override the type manually and specify the same value of the type of the column. If the dates passed to the specification contains time and are not reset to `00:00:00`, one possible workaround is to wrap the field into the `DATE` SQL function

**Comment by peter-gribanov** [comment]
Are you sure you need to reset the time?
```
mysql> select * from days where day > "2019-03-11 11:16:24";
+------------+
| day        |
+------------+
| 2019-03-12 |
+------------+
1 row in set (0.00 sec)
```

This will not work only in equality expressions.
```
mysql> select * from days where day = "2019-03-11 11:16:24";
Empty set (0.00 sec)
```
But what prevents to reset the time?
```
mysql> select * from days where day = "2019-03-11 00:00:00";
+------------+
| day        |
+------------+
| 2019-03-11 |
+------------+
1 row in set (0.01 sec)
```
With specifications
```php
Spec::eq('day', $time->setTime(0, 0, 0));
// or
Spec::eq('day', $time->format('Y-m-d'));
```
Specifications are intended to describe business rules. In the context of business rules, you know the data type of the filtered field and it is perfectly normal to bring the value that you have to this data type.

**Comment by peter-gribanov** [comment]
Now you can specify the data type explicitly:

```php
Spec::eq('day', Spec::value($time, Type::DATE));
```
