### ISSUE TITLE
Array to String converion in Field

### ISSUE THREAD

**Issue by patrickvale** [Happyr/Doctrine-Specification#187]
Thanks for all the updates :+1: 

I encountered a `Notice: Array to string conversion` in [Field](https://github.com/Happyr/Doctrine-Specification/blob/d93af0f2002155cf0e31a86291b59628962531ed/src/Operand/Field.php#L31)

Which I traced to [Spec::fun()](https://github.com/Happyr/Doctrine-Specification/blob/d93af0f2002155cf0e31a86291b59628962531ed/src/Spec.php#L690-L701) 

```php
    /**
     * @param string $functionName
     * @param mixed  $arguments
     *
     * @return PlatformFunction
     */
    public static function fun($functionName, $arguments = [])
    {
        $arguments = func_get_args();

        return new PlatformFunction(array_shift($arguments), $arguments);
    }
```

which calls ```$arguments = func_get_args();``` causing the ```$arguments``` array to be nested in another array, so that ```PlatformFunction``` constructs with ```$arguments``` as a nested array

```php
    /**
     * @var string
     */
    private $functionName = '';

    /**
     * @var array
     */
    private $arguments = [];

    /**
     * @param string $functionName
     * @param mixed  $arguments
     */
    public function __construct($functionName, $arguments = [])
    {
        if (2 === func_num_args()) {
            $this->functionName = $functionName;
            $this->arguments = (array) $arguments;
        } else {
            $arguments = func_get_args();
            $this->functionName = array_shift($arguments);
            $this->arguments = $arguments;
        }
    }
```

![image](https://user-images.githubusercontent.com/436585/56961422-ab2bbb80-6b4b-11e9-8f29-62cd0f90788d.png)

I created a exploratory fix on [this branch](https://github.com/patrickvale/Doctrine-Specification/blob/2e98a1b271f1067239ba5ee59e7421de6dd03701/src/Spec.php#L690-L706)

```php
    /**
     * @param string $functionName
     * @param mixed  $arguments
     *
     * @return PlatformFunction
     */
    public static function fun($functionName, $arguments = [])
    {
        $arguments = func_get_args();

        $name = array_shift($arguments);
        if (is_array($arguments)) {
            $arguments = array_map('end', $arguments);
        }

        return new PlatformFunction($name, $arguments);
    }
```

but I suspect the change ought to happen further into the library.

**Comment by peter-gribanov** [comment]
Can you check this #189 PR?
