### ISSUE TITLE
Missed alias for the Field spec

### ISSUE THREAD

**Issue by mitrae** [Happyr/Doctrine-Specification#195]
In example there is code usage `Spec::field('email','a')`  but in code only one argument is allowed

**Comment by mitrae** [comment]
Is there some other way to compare two fields from different tables/entities?

**Comment by peter-gribanov** [comment]
@mitrae  Thank for your report. Can you check this PR #196 ?

**Comment by mitrae** [comment]
thank you @peter-gribanov,  it is great library!
