### ISSUE TITLE
Mysql substring function bug

### ISSUE THREAD

**Issue by thehovdev** [Happyr/Doctrine-Specification#238]
This is not working

```php
Spec::SUBSTRING(Spec::field('last_name', 'pt'), 1, 1)
```

but this is working 

```php
Spec::SUBSTRING(Spec::field('last_name', 'pt'), new Value(1), 1)
```

**Comment by peter-gribanov** [comment]
Thanks for your report.

This is not quite a bug. The conversion of arguments was designed that way. It is not always possible to accurately determine where the Field operand should be and where the Value operand is. It is preferable to use operands in explicit form than to hope for implicit conversion.

By default, the first argument is converted to a Field operand, and the last to a Value operand. All intermediate arguments were not converted.
