### ISSUE TITLE
Disable Style CI

### ISSUE THREAD

**Issue by peter-gribanov** [Happyr/Doctrine-Specification#252]
The Style CI is a good service. It is based on PHP CS Fixer and uses similar rules. However, the rules for the Style CI and the PHP CS Fixer are identical and do not always work the same. What the PHP CS Fixer considers correct, the Style CI can mark as incorrect. We use the PHP CS Fixer during development, but we can use the Style CI only at the stage of testing a PR. Due to the differences in work, we are forced to launch Style CI and PHP CS Fixer at the stage of testing the PR #246. In this case, there is no particular need for the Style CI.

https://github.styleci.io/repos/21936868

**Comment by peter-gribanov** [comment]
@Nyholm can you check this?

**Comment by Nyholm** [comment]
I agree. 

It is disabled now

**Comment by peter-gribanov** [comment]
@Nyholm thanks :+1:
