### ISSUE TITLE
Best practices and architectural decissions

### ISSUE THREAD

**Issue by acelaya** [Happyr/Doctrine-Specification#276]
Hey!

First of all, amazing library. I've been struggling for some time to find a way to dinamically build incremental queries without having to nest too many repository methods, and this is allowing me to do it in a pretty maintainable way.

For now, I'm just using this library for one use case, but I plan to refactor some of my repositories which are too big and have signatures with many optional params.

I have one question, though, regarding what would be the best approach to handle specifications that are resolved dynamically (or even statically, to be honest).

> Bear with me for the long text coming next 😅 

I usually have at least 3 layers in my projects: Controller/Action -> Service/Domain -> Repository/Persistence. In some cases, there could be one or two extra layers in between.

With this in mind, I'm struggling to determine what's the best way to use Specifications.

* Should I pass them to the repository's `match*` methods from the upper layers?
* Should I create new repository methods where I make use of the required specs to avoid leaking the spec details to upper layers?

I'm currently doing the latter in most of the cases when I'm using a "static" set of specs, or even to build simple specs on the fly, but then, I end up having to create new methods in repositories, which defeats the purpose of simplifying them.

For example, I had this method in a service:

```php
public function listTags(): array
    /** @var TagRepository $repo */
    $repo = $this->em->getRepository(Tag::class);
    return $repo->findBy([], ['name' => 'ASC']);
}
```

Which becomes this with specs.

```php
public function listTags(): array
    /** @var TagRepository $repo */
    $repo = $this->em->getRepository(Tag::class);
    return $repo->match(Spec::orderBy('name'));
}
```

Should I move the use of specs to the repository on a new method, called `findTags`, for example?

Probably this is an oversimplified case and we could live with it, but the actual use case comes because I'm now "piping" more specs dynamically, based on a new param.

```php
public function listTags(ApiKey $apiKey): array
{
    /** @var TagRepository $repo */
    $repo = $this->em->getRepository(Tag::class);
    return $repo->match(Spec::andX(
        Spec::orderBy('name'),
        new WithApiKeySpecsEnsuringJoin($apiKey),
    ));
}
```

The `WithApiKeySpecsEnsuringJoin` class extends `BaseSpecification`, and allows me to pipe more specs dynamically, based on the API key roles/permissions.

Should everything be moved to the repository in this case, and have it expose something like `findTagsForApiKey(ApiKey $apiKey): array`?

Well, this is just me thinking out loud, haha. I will probably come up with what "feels right" after using it for a while and having done a few rounds of refactoring, but I wanted to know what you think, as authors of the library.

As I said, I love how you implemented the pattern. Well done 👏🏼

**Comment by peter-gribanov** [comment]
I am not the author of this project and i have no clear opinion on your question. Some of my thoughts.

> * Should I pass them to the repository's `match*` methods from the upper layers?
> * Should I create new repository methods where I make use of the required specs to avoid leaking the spec details to upper layers?

The idea behind this project is to just abandon methods like `findTagsForApiKey()`, `listTags()`.

The [specifications](https://en.m.wikipedia.org/wiki/Specification_pattern) are the domain level, not the persistence level. It is normal to use domain elements at the upper levels. After the implementation of feature #273, it will be possible to apply specifications not only for selecting entities from the repository, but also for checking specific entities and entities collection. This is another reason to use specifications not only at the persistence level.

I also want to say that business processes can also have a repository. This means that the business layer will contain the repository interface, and its implementation will be at the persistence layer. There are persistence operations that need to be optimized, but these changes should not be reflected at the business logic level. That is, sometimes it is really better to have a repository with a set of methods for different selections.

You can also look at this issue from the point of view of separating read and write streams as in CQRS. This is not about creating commands and queries, but about the business logic being only in the write stream, and the read stream being separate and aimed at optimizing performance.

**Comment by acelaya** [comment]
> The specifications are the domain level, not the persistence level. It is normal to use domain elements at the upper levels

👍🏼 

I would probably try to wrap my own specs us much as possible though, and not spread too many `Spec::andX(...)` all around.

> I also want to say that business processes can also have a repository. This means that the business layer will contain the repository interface, and its implementation will be at the persistence layer. There are persistence operations that need to be optimized, but these changes should not be reflected at the business logic level. That is, sometimes it is really better to have a repository with a set of methods for different selections.

Do you mean by this that you would use specs in business layers as much as possible, without defining new methods in the repositories, and only create new repository methods when optimization is important and you need to "get your hands dirty" with raw DQL/SQL?

**Comment by peter-gribanov** [comment]
> I would probably try to wrap my own specs us much as possible though, and not spread too many `Spec::andX(...)` all around.

👍

> Do you mean by this that you would use specs in business layers as much as possible, without defining new methods in the repositories, and only create new repository methods when optimization is important and you need to "get your hands dirty" with raw DQL/SQL?

In our project, we use a repository with all the necessary methods explicitly declared. In these methods, we use specifications. This simplifies the construction of queries, reduces code duplication, facilitates the management of business rules and allows us to build queries describing them in terms of the domain, not a DQL. But we still create a repository with many methods.
I do not want to say that this is the best solution, but so far it suits us.

**Comment by acelaya** [comment]
Ok, I wasn't sure what you meant.

Yeah, that's also the approach with which I have started using the library.

**Comment by acelaya** [comment]
Since my original question is answered, I'll close the issue. Thanks a lot for the input @peter-gribanov 🙂
