### ISSUE TITLE
Use defaultRepositoryClassName instead of the RepositoryFactory

### ISSUE THREAD

**Issue by thexpand** [Happyr/Doctrine-Specification#297]
I find it more convenient to use the `defaultRepositoryClassName` of the Doctrine configuration. Your `RepositoryFactory` seems to be a bit harsh and doesn't take into account if I currently have entities with their own custom repositories, which makes it hard to refactor a large codebase gradually. I ended up setting `EntitySpecificationRepository` as the default repository class name. This way I'm still using the default repository factory that is provided by Doctrine, which will create the specification repository as a fallback. When I want to, I can use the `EntitySpecificationRepositoryTrait` trait in the current repositories and from there I can gradually refactor the methods into specifications.

Do you think that this should be included somewhere in the documentation, because now it only suggests to use the factory?

**Comment by peter-gribanov** [comment]
> I ended up setting `EntitySpecificationRepository` as the default repository class name. This way I'm still using the default repository factory that is provided by Doctrine, which will create the specification repository as a fallback. When I want to, I can use the `EntitySpecificationRepositoryTrait` trait in the current repositories and from there I can gradually refactor the methods into specifications.

This is what the documentation for [Symfony](https://github.com/Happyr/Doctrine-Specification/blob/b21831c6070a2127352b2ab4033b60ba0f6cc052/docs/0-0-symfony.md)  and [Laravel](https://github.com/Happyr/Doctrine-Specification/blob/b21831c6070a2127352b2ab4033b60ba0f6cc052/docs/0-3-laravel.md) suggests to do.
Perhaps you are looking at the documentation for [Zend 1](https://github.com/Happyr/Doctrine-Specification/blob/b21831c6070a2127352b2ab4033b60ba0f6cc052/docs/0-1-zend1.md) or [Zend 2](https://github.com/Happyr/Doctrine-Specification/blob/b21831c6070a2127352b2ab4033b60ba0f6cc052/docs/0-2-zend2.md)? For Zend, the documentation does suggest using a factory.

**Comment by peter-gribanov** [comment]
I think we can make another factory that allows custom repositories. But i'm not sure if that makes sense since it will act as a Doctrine repository factory. I would say that using the `default_repository_class` option is the preferred solution.

**Comment by thexpand** [comment]
I see now that there has been a PR that is already merged. Shall I close this issue now?

**Comment by peter-gribanov** [comment]
Yes. Of course.
