### ISSUE TITLE
Psalm annotations

### ISSUE THREAD

**Issue by loevgaard** [Happyr/Doctrine-Specification#304]
Hi

Thanks for this great library. Would it make sense to add template annotations to the `\Happyr\DoctrineSpecification\Repository\EntitySpecificationRepositoryInterface` just as Doctrine has it in `\Doctrine\Persistence\ObjectRepository`? This way I wouldn't have to add `@var` annotations in something like this: 

```php
/** @var array<array-key, JobInterface> $jobs */
$jobs = $this->jobRepository->match(new Running());
```

I can provide a PR if you think it makes sense :)

**Comment by peter-gribanov** [comment]
Good idea :+1:

**Comment by peter-gribanov** [comment]
@loevgaard will you make a PR or should i? I would like to keep the authorship for you.

**Comment by loevgaard** [comment]
Hi, Peter

I won't make it before after summer, around week 35 would be my best guess. If you make it, you don't have to do anything about the ownership. I am just very happy with this package :)

**Comment by peter-gribanov** [comment]
Unfortunately, this cannot be done. Essence will not always be the result. #307

**Comment by loevgaard** [comment]
Ah, I see. That's a pity :( Thanks for giving it a shot!
