### ISSUE TITLE
Left Join as default?

### ISSUE THREAD

**Issue by HKandulla** [Happyr/Doctrine-Specification#320]
Hi,
currently inner join is used if a context is given. 
For Example:

    $spec = Spec::orX(
      Spec::eq('customer', $agency->getCustomer(), 'agency'),
      Spec::eq('customer', $advertiser->getCustomer(), 'advertiser')
    );

resolves to:

    SELECT root FROM App\Entity\PackageOrder root INNER JOIN root.agency agency INNER JOIN root.advertiser advertiser WHERE agency.customer = :comparison_0 OR advertiser.customer = :comparison_1

This means that only rows are returned that satisfy the inner join. Wouldn't it make more sense to use left join as the default and only inner join if added explicitly?

Thanks, Hannes

**Comment by peter-gribanov** [comment]
The LEFT JOIN is heavier than the INNER JOIN. It should be avoided if possible.
You can always explicitly use LEFT JOIN (`Spec::leftJoin()`) where necessary.

**Comment by HKandulla** [comment]
Hi @peter-gribanov ,
ok, thanks for the insight and all the goos work! I will close this issue.

**Comment by peter-gribanov** [comment]
Join contexts are done in [DQLContextResolver](https://github.com/Happyr/Doctrine-Specification/blob/2.x/src/DQLContextResolver.php#L82). You can try changing the type to the one you need. If the performance suits you, then make a PR to add the ability to configure the default join option when resolving the context.
