### ISSUE TITLE
Use Query instead of AbstractQuery

### ISSUE THREAD

**Issue by Nyholm** [Happyr/Doctrine-Specification#40]
The discussion on #39 made me convinced that we should use Query instead of AbstractQuery in the method declaration of modifyQuery.

From the `EntitySpecificationRepository`:

``` php
$query = $qb->where($expr)->getQuery();

//give the Specification a change to modify the query
$specification->modifyQuery($query);
```

**Comment by peter-gribanov** [comment]
@Nyholm in my opinion this task is no longer relevant. This is true?

**Comment by Nyholm** [comment]
Correct. Closing this issue.
