### ISSUE TITLE
define an interface for the specification repository

### ISSUE THREAD

**Issue by cordoval** [Happyr/Doctrine-Specification#53]
I have a case with
class UserGroupRepository extends NestedTreeRepository

so it is hard to make it extend also the base class, however there is not an interface

**Comment by Nyholm** [comment]
Closed by #87.

**Comment by thundo** [comment]
The trait is nice and fine for repositories with inheritance, but wouldn't be nicer to have an interface too?

**Comment by Nyholm** [comment]
Sure @thundo, Send a PR and I'll merge it.
